### ISSUE TITLE
Úkol č. 5 - dědičnost

### ISSUE THREAD

**Issue by helenafanfrlikova** [helenafanfrlikova/python-autumn-2022#6]
https://github.com/helenafanfrlikova/python-autumn-2022/blob/main/ukol-05-dedicnost.py

Ahoj,

zkouším udělat tento další úkol, ale i když ten výstup odpovídá zadání, tak stejně tam mám asi něco špatně.

V řádku 17 mám ten parametr "varianty" šedý, takže to asi není správně, ale zkoušela jsem to různě měnit a vždycky tam byl pak jiný problém.
Když "varianty" v řádku 17 smažu, tak to zase na konci nefunguje s argumentem "omikron" podle zadání úkolu (Příklad použití: corona = Koronavirus('Coronavirus', ['omikron'])), protože je to pak o jeden poziční argument víc.
I v tom zadání úkolu - "Příkladu použití" se mi to zdá nelogické - když už jsem zadala ten omikron v parametrech objektu corona, tak proč by to hlásilo "žádné nalezené varianty"? Totéž, když jsem pak zkoušela přidat nový objekt ze třídy Koronavirus, tak když mu nadefinuju v argumentech variantu, tak mi to pak stejně hlásí "žádné nalezené varianty".

Asi to vysvětluju zmateně, jak už se do toho zamotávám, snad to pochopíš z toho kódu, kde mám problém.

Plus dotaz na bod v zadání:
"Ze tridy Nemoc dedi beze zmeny chovani:
Atribut jmeno
Metodu zmen_pocet_obeti" - když se ta metoda u třídy Koronavirus nemění, tak ji nemusím znovu opakovat, ne?

Moc díky!
H.

**Comment by pmoravkova** [comment]
Ahoj, mas to velmi dobre!
Proc to mas sedivy - protoze to mas argument funkce, ale funkce si VSCode si mysli, ze jsi ten argument ve funkci nepouzila, proto je nadbytecny. Idealne bys to mohla udelat takhle, ale je to vlastne v tuhle chvili to same:
```
class Koronavirus(Nemoc):
    def __init__(self, jmeno, varianty = []):
        super().__init__(jmeno, 12, 1000, "vzduchem")
        self.varianty = varianty
```
Co se tyce u toho prikladu pouziti. Tam to mas tez dobre. Ono kdyz se totiz podivas do git historie zadani ukolu, tak tam puvodne bylo ne `corona = Koronavirus('Coronavirus', ['omikron'])`, ale bylo to `corona = Koronavirus('Coronavirus', 'omikron')`, takze tam byla ukazka stringu jmena varianty a do seznamu varianty jste to dodavali az vy, proto byl zezacatku prazdny seznam a v ukazce printu u toho prikladu pouziti. To je chyba v zadani, napisu to Andy. Diky za povsimnuti.

**Comment by helenafanfrlikova** [comment]
Ahoj Pavlo,

moc díky, tím se to vysvětluje 😊,

Helena
